### ISSUE TITLE
Does FASText support chinese text detection?

### ISSUE THREAD

**Issue by albertyou2** [MichalBusta/FASText#16]
HI @MichalBusta
Does FASText support chinese text detection?
Or Is there any way to train for chinese text? 
Thank you !

**Comment by MichalBusta** [comment]
Hi, 
generally yes: there are just 2 assumption behind: 
  - text fragments are formed of strokes and they are locally separable in the intensity channel

I would expect, that the provided classifier will work reasonably well even on chinese text, since the main features are "strokeness' and 'compatness'.

**Comment by albertyou2** [comment]
ok ，i will try this 
thank you again !
